name: Kaggle Notebooks Sync

on:
  workflow_dispatch:  # Manually trigger the workflow
  schedule:
    - cron: '0 0 * * *'  # Daily automatic run (optional)

jobs:
  sync-kaggle-notebooks:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install kaggle pandas

    - name: Configure Kaggle API
      run: |
        mkdir -p ~/.kaggle
        echo '{"username":"${{ secrets.KAGGLE_USERNAME }}","key":"${{ secrets.KAGGLE_KEY }}"}' > ~/.kaggle/kaggle.json
        chmod 600 ~/.kaggle/kaggle.json

    - name: Download Kaggle notebooks list
      run: |
        kaggle kernels list --csv > kaggle_notebooks.csv

    - name: Convert to JSON
      run: |
        ls

    - name: Download notebooks and metadata
      run: |
        ls

    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add .
        git commit -m "Automated update: Kaggle notebooks sync"
        git push
