name: Sync Kaggle Notebooks

on:
  schedule:
    # Runs daily at 12:00 UTC (customize the cron schedule as needed)
    - cron: "0 12 * * *"
  workflow_dispatch: # Allow manual triggering

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Kaggle API
        run: pip install kaggle

      - name: Configure Kaggle API
        env:
          KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
          KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
        run: |
          mkdir -p ~/.kaggle
          echo '{"username":"'$KAGGLE_USERNAME'","key":"'$KAGGLE_KEY'"}' > ~/.kaggle/kaggle.json
          chmod 600 ~/.kaggle/kaggle.json

      - name: Download Kaggle Notebooks
        run: |
          # List all your Kaggle notebooks and download them
          kaggle kernels list --mine | grep -oP '(?<=,)[^,]+$' | while read slug; do
            kaggle kernels pull "$slug" -p notebooks/ --force
          done

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add notebooks/*
          git commit -m "Automated sync: Update Kaggle notebooks" || echo "No changes to commit"
          git push origin main
