name: Sync Kaggle Notebooks

on:
  schedule:
    - cron: "0 12 * * *"  # Daily at 12:00 UTC
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Kaggle API and Dependencies
        run: |
          pip install kaggle
          sudo apt-get install -y jq  # Install JSON parser for processing Kaggle API output

      - name: Configure Kaggle API
        env:
          KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
          KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
        run: |
          mkdir -p ~/.kaggle
          echo '{"username":"'$KAGGLE_USERNAME'","key":"'$KAGGLE_KEY'"}' > ~/.kaggle/kaggle.json
          chmod 600 ~/.kaggle/kaggle.json

      - name: Download Kaggle Notebooks
        run: |
          # Create notebooks directory if it doesn't exist
          mkdir -p notebooks

          # List all Kaggle notebooks and download them
          kaggle kernels list --mine --json | jq -r '.[].id' | while read slug; do
            echo "Downloading notebook: $slug"
            kaggle kernels pull "$slug" -p "notebooks/"  # Removed --force
          done

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add notebooks/*
          git diff --quiet && git diff --staged --quiet || (git commit -m "Automated sync: Update Kaggle notebooks" && git push origin main)
