name: Sync Kaggle Notebooks

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Kaggle CLI
        run: pip install kaggle

      - name: Configure Kaggle API
        env:
          KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
          KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
        run: |
          mkdir -p ~/.kaggle
          echo "{\"username\":\"$KAGGLE_USERNAME\",\"key\":\"$KAGGLE_KEY\"}" > ~/.kaggle/kaggle.json
          chmod 600 ~/.kaggle/kaggle.json

      - name: Fetch All Notebooks List
        run: |
          page=1
          while true; do
            kaggle kernels list --mine --page $page --csv >> notebooks.csv
            if [ $(wc -l < notebooks.csv) -ge $(($page * 20)) ]; then
              ((page++))
            else
              break
            fi
          done

      - name: Download Kaggle Notebooks
        run: |
          kaggle kernels list --mine --sort-by dateCreated --output-format json | jq -r '.[].ref' > notebooks.txt
          mkdir -p kaggle_notebooks
          while read notebook; do
            kaggle kernels pull "$notebook" -p kaggle_notebooks --metadata --force
          done < notebooks.txt

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add kaggle_notebooks
          git commit -m "Sync Kaggle notebooks" || echo "No changes to commit"
          git push
