name: Sync Kaggle Notebooks to GitHub

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual execution

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Kaggle CLI
        run: pip install kaggle

      - name: Configure Kaggle API
        run: |
          mkdir -p ~/.kaggle
          echo "{\"username\":\"${{ secrets.KAGGLE_USERNAME }}\",\"key\":\"${{ secrets.KAGGLE_KEY }}\"}" > ~/.kaggle/kaggle.json
          chmod 600 ~/.kaggle/kaggle.json

      - name: Download Kaggle Notebooks
        run: |
          mkdir -p kaggle_notebooks
          cd kaggle_notebooks
          kaggle kernels list --mine --csv | tail -n +2 | cut -d ',' -f1 | while read notebook; do
            kaggle kernels pull "$notebook" -p "$notebook" --metadata
          done
          cd ..

      - name: Commit and Push Changes
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Sync latest Kaggle notebooks" || echo "No changes to commit"
          git push
